name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-testfleeeeet-${{ github.run_id }}-${{ github.run_attempt }}
      - fleet:MediumSizeFleet-zXolqX218byu
      - image:arm-3.0
      - instance-size:large
    steps:
      - run: echo "Hello World ula!"
